# Generated by Django 4.0 on 2021-12-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='borrower_level',
            field=models.CharField(default='iron', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cash',
            field=models.DecimalField(decimal_places=3, default=100000, max_digits=15),
        ),
    ]
